In [4]:
from pandas import Series
from sklearn.preprocessing import MinMaxScaler

In [5]:
#define contrived series
data = [10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0]
series = Series(data)
print(series)

0     10.0
1     20.0
2     30.0
3     40.0
4     50.0
5     60.0
6     70.0
7     80.0
8     90.0
9    100.0
dtype: float64


In [6]:
#prepare data for normalization
values = series.values
values = values.reshape((len(values),1))

In [8]:
#train the normalization
scaler = MinMaxScaler(feature_range=(0,1))
scaler = scaler.fit(values)

In [9]:
print('Min: %f, Max: %f' % (scaler.data_min_, scaler.data_max_))

Min: 10.000000, Max: 100.000000


In [10]:
#normalize the dataset and print
normalized = scaler.transform(values)
print(normalized)

[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [0.44444444]
 [0.55555556]
 [0.66666667]
 [0.77777778]
 [0.88888889]
 [1.        ]]


In [12]:
#inverse transform and print
inversed = scaler.inverse_transform(normalized)
print(inversed)

[[ 10.]
 [ 20.]
 [ 30.]
 [ 40.]
 [ 50.]
 [ 60.]
 [ 70.]
 [ 80.]
 [ 90.]
 [100.]]


## Standardization

In [33]:
from sklearn.preprocessing import StandardScaler
from math import sqrt

In [34]:
#define contrived series
data = [1.0, 5.5, 9.0, 2.6, 8.8, 3.0, 4.1, 7.9, 6.3]
series = Series(data)
print(series)

0    1.0
1    5.5
2    9.0
3    2.6
4    8.8
5    3.0
6    4.1
7    7.9
8    6.3
dtype: float64


In [35]:
#prepare data for normalization
values = series.values
values = values.reshape((len(values), 1))

In [36]:
#train the normalization
scaler = StandardScaler()
scaler = scaler.fit(values)

In [37]:
print('Mean: %f, StandardDeviation: %f' % (scaler.mean_, sqrt(scaler.var_)))

Mean: 5.355556, StandardDeviation: 2.712568


In [38]:
#noramalize the dataset and print
standardized = scaler.transform(values)
print(standardized)

[[-1.60569456]
 [ 0.05325007]
 [ 1.34354035]
 [-1.01584758]
 [ 1.26980948]
 [-0.86838584]
 [-0.46286604]
 [ 0.93802055]
 [ 0.34817357]]


In [39]:
scaler.fit(standardized)
print('Mean: %f, StandardDeviation: %f' % (scaler.mean_, sqrt(scaler.var_)))

Mean: -0.000000, StandardDeviation: 1.000000


In [40]:
#inverse transform and print
inversed = scaler.inverse_transform(standardized)
print(inversed)

[[-1.60569456]
 [ 0.05325007]
 [ 1.34354035]
 [-1.01584758]
 [ 1.26980948]
 [-0.86838584]
 [-0.46286604]
 [ 0.93802055]
 [ 0.34817357]]
