In [61]:
from keras.models import Sequential
from keras.layers.convolutional import Conv2D, MaxPooling2D
from keras.layers.core import Flatten, Dense
from keras.layers.recurrent import LSTM
from keras.layers import Activation
from keras.optimizers import SGD
from numpy import array
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [34]:
# model = Sequential()
# model.add(LSTM(2))
# model.add(Dense(1))

#we can also do this :
#layers = [LSTM(2), Dense(1)]
#model = Sequential(layers)

In [35]:
data = np.arange(20).reshape(2, 10)
print(data)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [36]:
data = data.reshape((data.shape[0], data.shape[1], 1))

In [37]:
print(data)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]]]


In [38]:
data = data.reshape((data.shape[0], 1, data.shape[1]))
print(data)

[[[ 0  1  2  3  4  5  6  7  8  9]]

 [[10 11 12 13 14 15 16 17 18 19]]]


In [39]:
model = Sequential()
model.add(LSTM(5, input_shape=(2,1)))
model.add(Dense(1))
model.add(Activation('sigmoid'))

In [43]:
algorithm = SGD(lr=0.1, momentum=0.3)
model.compile(optimizer=algorithm, loss='mean_squared_error', metrics=['accuracy'])

In [44]:
data

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]])

In [45]:
data.shape

(2, 1, 10)

In [46]:
data = array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])

In [48]:
print(data)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [49]:
data = data.reshape((1, 10, 1))

In [119]:
print(data.shape)

(1, 2, 1)


In [131]:
model2 = Sequential()
model2.add(LSTM(32, input_shape=(10,2)))
model2.add(Dense(10))
#model2.add(Activation('softmax'))

In [132]:
algorithm = SGD(lr=0.1, momentum=0.3)
model2.compile(optimizer=algorithm, loss='categorical_crossentropy', metrics=['accuracy'])

In [133]:
data = array([
[0.1, 1.0],
[0.2, 0.9],
[0.3, 0.8],
[0.4, 0.7],
[0.5, 0.6],
[0.6, 0.5],
[0.7, 0.4],
[0.8, 0.3],
[0.9, 0.2],
[1.0, 0.1]])

In [134]:
print(data)

[[0.1 1. ]
 [0.2 0.9]
 [0.3 0.8]
 [0.4 0.7]
 [0.5 0.6]
 [0.6 0.5]
 [0.7 0.4]
 [0.8 0.3]
 [0.9 0.2]
 [1.  0.1]]


In [140]:
data = data.reshape(1, 10, 2)
print(data.shape)
print(data)

(1, 10, 2)
[[[0.1 1. ]
  [0.2 0.9]
  [0.3 0.8]
  [0.4 0.7]
  [0.5 0.6]
  [0.6 0.5]
  [0.7 0.4]
  [0.8 0.3]
  [0.9 0.2]
  [1.  0.1]]]


In [136]:
out = array(['A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J'])

In [137]:
print(out)

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']


In [138]:
ohe = OneHotEncoder(sparse=False)
out = out.reshape(len(out), 1)
out_en = ohe.fit_transform(out)
print(out_en)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [139]:
history = model2.fit(data, out_en, batch_size=2, epochs=100)

ValueError: Input arrays should have the same number of samples as target arrays. Found 1 input samples and 10 target samples.

In [117]:
data1 = np.arange(2).reshape(1, 2, 1)
print(data1)

[[[0]
  [1]]]
